table 'usuario_rol?select=*'
	lineageTag: 67b72bda-4794-4490-9abf-45a704f0265d

	column usuario_id
		dataType: int64
		formatString: 0
		lineageTag: b8d5f0dd-5c6e-4b44-9a73-ef4d2ae01ed0
		summarizeBy: none
		sourceColumn: usuario_id

		annotation SummarizationSetBy = Automatic

	column rol_id
		dataType: int64
		formatString: 0
		lineageTag: 75698a1c-2fc5-4ffd-82f4-298fe51e78bc
		summarizeBy: none
		sourceColumn: rol_id

		annotation SummarizationSetBy = Automatic

	partition 'usuario_rol?select=*' = m
		mode: import
		source =
				let
				    Origen = Json.Document(Web.Contents("https://todqutcrfyuqdqckjhlt.supabase.co/rest/v1/usuario_rol?select=*", [Headers=[apikey="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZHF1dGNyZnl1cWRxY2tqaGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODczNzYsImV4cCI6MjA2MTQ2MzM3Nn0.HjZ6YxCYUKj2m5aaydriz-ZFQl93M7kyUGCxM1Hjwr4", Authorization="Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvZHF1dGNyZnl1cWRxY2tqaGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4ODczNzYsImV4cCI6MjA2MTQ2MzM3Nn0.HjZ6YxCYUKj2m5aaydriz-ZFQl93M7kyUGCxM1Hjwr4", Accept="application/json"]])),
				    #"Convertida en tabla" = Table.FromList(Origen, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Se expandió Column1" = Table.ExpandRecordColumn(#"Convertida en tabla", "Column1", {"usuario_id", "rol_id"}, {"usuario_id", "rol_id"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Se expandió Column1",{{"usuario_id", Int64.Type}, {"rol_id", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

